version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=sqlite:///app.db
      - GMAIL_PASSWORD=Your_Password
      - GMAIL_ID=your_gmail
      - PORT=3000
      - EMAIL_PORT=465
      - OPEN_WEATHER_API_KEY=YourAPIKEY
    volumes:
      - .:/app
